
version: '3.9'

services:
    mongo:
        image: mongo:latest
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "pass2021"
        volumes:        
            - mongodb-data:/data/db
        networks:
            - mongodb-net
        restart: always
        ports:
            - "27017:27017"
        command: mongod

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        environment:
            ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
            ME_CONFIG_BASICAUTH_USERNAME: "admin"
            ME_CONFIG_BASICAUTH_PASSWORD: "pass9999"
            ME_CONFIG_MONGODB_SERVER: "mongo"
            ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
            ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
            ME_CONFIG_MONGODB_ADMINPASSWORD: "pass2021"
        networks:
            - mongodb-net
        ports:
            - "8081:8081"
        depends_on:
            - mongo
        restart: unless-stopped
        volumes:
            - mongodb-data

networks:
    mongodb-net:
        name: mongodb-net
        driver: bridge

volumes:
    mongodb-data:
        name: mongodb-data